const starApiConstants = {
  arrival: 'arrivee',
  theoreticalArrival: 'arriveetheorique',
  precision: 'precision',
  smallLineName: 'nomcourtligne',
  stopName: 'nomarret',
  destination: 'destination',
  courseId: 'idcourse',
  stopId: 'idarret',
  id: 'id',
  coordinates: 'coordonnees',
  smallName: 'nomcourt',
  commercialFamilyName: 'nomfamillecommerciale',
  textLineColor: 'couleurtexteligne',
  lineColor: 'couleurligne',
  longName: 'nomlong',
  ticketingId: 'idbillettique',
  lineId: 'idligne',
  type: 'type',
  longDescription: 'libellelong',
  routeId: 'idparcours',
  order: 'ordre',
  arrivalStopName: 'nomarretarrivee',
  startStopId: 'idarretdepart',
  arrivalStopId: 'idarretarrivee',
  comingMainRouteId: 'idparcoursprincipalretour',
  goingMainRouteId: 'idparcoursprincipalaller',
  direction: 'sens',
  city: 'nomcommune',
  name: 'nom',
};

export { starApiConstants };
